# Generated by Django 3.0.5 on 2020-08-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
    ]
